.github/issue_template.md

Change the location so it will be automatically picked up when you create an issue. Was annoying me i had to either pick the template or click a small button to get a clean one. Now you can just empty it.

Change git issue template location

---

README.md

I've added `stryker4s` to the `bettercodehub` so we can get some general static code analysis. It should be triggered when a new branch is build/merged i think. If not we can look for a replacement that does so. 
Alternative could be `Codecov` for example

Add Better code badge

---

core/src/main/scala/stryker4s/Stryker4s.scala
core/src/main/scala/stryker4s/model/MutantRunResult.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
core/src/main/scala/stryker4s/run/ProcessMutantRunner.scala
core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/FileCollectorTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantFinderTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
docs/MUTATORS.md
project/Dependencies.scala
util/src/main/scala/stryker4s/extensions/TreeExtensions.scala
util/src/main/scala/stryker4s/extensions/mutationtypes/LiteralMutationTypes.scala
util/src/main/scala/stryker4s/extensions/mutationtypes/TermNameMutationTypes.scala
util/src/test/scala/stryker4s/extensions/TreeExtensionsTest.scala
util/src/test/scala/stryker4s/extensions/mutationtypes/MutationTypesTest.scala

I've added 12 new mutators and updated the documentation to reflect it. The new mutators are mostly function mutators. This takes the number of found mutants when running stryker4s on stryker4s from 10 to 62. It puts our new own mutation score at 77%.
There are probably still a lot of other mutators we can/should add. Can be discussed in #11.
I also did a short experiment with changing `Some(a)` to `None` and `option.getOrElse(a)` to `option.get`. 
The first caused compile errors in some areas, due to the type of the Option no longer being known. We might have to look into this again once we have compile error rollback.
With the second I ran into some troubles with having to replacing a function that has arguments to a function with no arguments. It sounds simple, I know. But we might …

Add new mutators

---

build.sbt
core/src/test/scala/stryker4s/run/report/HtmlReporterTest.scala
project/Dependencies.scala
project/Settings.scala
util/src/test/scala/stryker4s/MutationTestingElementsJsonSchema.scala

Plumming so we will be able to retrieve the json schema from unpkg and a json validator that will validate the output of the html reporter against the schema. This is for now a static json this should be improved when the html reporter is being implemented.
Fixes: #51

Validate html reporter output with json schema

---

core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
core/src/test/scala/stryker4s/mutants/MutatorTest.scala
core/src/test/scala/stryker4s/run/report/ReporterTest.scala
util/src/test/scala/stryker4s/Stryker4sSuite.scala
util/src/test/scala/stryker4s/TestAppender.scala
util/src/test/scala/stryker4s/scalatest/LogMatchers.scala

I rewrote the logMatcher + appender so it's safe to use.
Basically how it works is by adding a class name so the reset function only removes log events for that specific class under test. because of the AfterEach which is used to reset this is perfectly safe. 
Also altered the log matchers to include the class name so if 2 different classes would log the same line the matchers would still match correctly. This is also done by including the class name.
One warning: It does require a 1:1 mapping of the package structure for the tests. But this is a good practice to do anyway.
this will fix #44

Logging tests without race conditions

---

core/src/main/scala/stryker4s/mutants/findmutants/MutantFinder.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantFinderTest.scala
project/Dependencies.scala

I've updated Scalameta to the new 4.0.0 release. This fixes a couple of issues we had with older versions (namely https://github.com/scalameta/scalameta/issues/1597 and https://github.com/scalameta/scalameta/issues/1526) and allows a small code cleanup. I've also updated some other dependencies while I was there.

Update to Scalameta 4.0.0 (and some other dependencies)

---

core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
core/src/test/scala/stryker4s/mutants/MutatorTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantFinderTest.scala
core/src/test/scala/stryker4s/run/report/ReporterTest.scala
util/src/test/scala/stryker4s/Stryker4sSuite.scala
util/src/test/scala/stryker4s/scalatest/LogMatchers.scala

Refactors the logging test code into `LogMatcher`. This way, tests only have to extend `LogMatcher` to test logs, instead of also having to extend `BeforeAndAfterEach`. Tests now also don't have to call the `afterEach` to reset logs, but this is done automatically when extending `LogMatcher`. Also, because the implicit className is no longer in `Stryker4sSuite`, compile times are theoretically a little faster.

Refactor all logging test code into LogMatcher

---

core/src/main/scala/stryker4s/model/Mutant.scala
core/src/main/scala/stryker4s/mutants/applymutants/StatementTransformer.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
core/src/test/scala/stryker4s/Stryker4sTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/StatementTransformerTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
core/src/test/scala/stryker4s/run/process/ProcessMutantRunnerTest.scala
util/src/main/scala/stryker4s/extensions/mutationtypes/LogicalOperators.scala
util/src/main/scala/stryker4s/extensions/mutationtypes/MutationTypes.scala

In the HTML reporter spec is a field called "mutatorName" so far we were not able to get this field filled. But with this merge request and because of the removal of the useless case classes we are able to do it in a semi-elegant way.

Add names to mutants so we can have it in the html report

---

core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
util/src/main/scala/stryker4s/extensions/mutationtypes/MutationTypes.scala

Fixes #65 
Adds a matching condition on a Mutation. If it's a Term.Name, check if the tree is a definition or not (it shouldn't be)

Fix matching on function names and add tests

---

core/src/main/scala/stryker4s/run/ProcessMutantRunner.scala
util/src/main/scala/stryker4s/extensions/score/MutationScoreCalculator.scala
util/src/test/scala/stryker4s/extensions/score/MutationScoreCalculatorTest.scala

Currently, when the configuration is wrong and you will not find any mutations the mutation score calculation will do a divide by zero. 
Scala's behavior is not a DivideByZeroException by a NaN. This merge request will putt a check if it's a `NaN` and convert that back to a `0.00`

Improve calculation of mutation score

---

core/src/main/scala/stryker4s/extensions/FileExtensions.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantFinder.scala
core/src/main/scala/stryker4s/run/ProcessMutantRunner.scala
core/src/test/scala/stryker4s/extensions/FileExtensionsTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantFinderTest.scala

I've removed the `Parsed file: ...` debug log as it was causing a lot of random test failures, and didn't add much. Any error during parsing should already log the causing file.. 
I've also added a .relativePath extension method on `File` for ease of use

Remove debug statement and add relativePath extension method

---

core/src/main/resources/logback.xml
core/src/main/scala/stryker4s/Stryker4s.scala
core/src/main/scala/stryker4s/config/Config.scala
core/src/main/scala/stryker4s/mutants/findmutants/FileCollector.scala
core/src/test/resources/stryker4sconfs/filled.conf
core/src/test/resources/stryker4sconfs/wrongReporter.conf
core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
core/src/test/scala/stryker4s/config/ConfigTest.scala
core/src/test/scala/stryker4s/mutants/MutatorTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/FileCollectorTest.scala
core/src/test/scala/stryker4s/stubs/TestSourceCollector.scala
docs/CONFIGURATION.md

Changed the config settings `files` to `mutate` this is also reflected in [Stryker config](https://github.com/stryker-mutator/stryker/blob/master/packages/stryker/README.md#configuration)
Also, we need the `files` settings as a backup plan on collecting files to copy over files to the tmp folder.

Change config setting files to mutate

---

build.sbt

As reported on Gitter it was not possible to run `sbt run` from the root of the project.
This will make it possible to run `sbt run` from the root of the project.

Fix sbt so it can be run from the root

---

project/Dependencies.scala

Bringing [up to 10% improvement in compiler performance](https://github.com/scala/scala/releases/tag/v2.12.7). Which is always a nice thing to have

Update scala from 2.12.6 to 2.12.7

---

core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/StatementTransformerTest.scala
util/src/main/scala/stryker4s/extensions/TreeExtensions.scala
util/src/test/scala/stryker4s/extensions/TreeExtensionsTest.scala

Fixes #48 
Also cleaned up the syntax of the `ImplicitTermExtensions` a little bit. Hopefully it's a little clearer. `||` and `&&` (and other infix apply's) are now also included in the top statement, which might make the resulting pattern match a little bigger, but will likely prevent some other compile errors

Fix literal pattern match not being included in top statement

---

core/src/main/scala/stryker4s/run/ProcessMutantRunner.scala
core/src/test/scala/stryker4s/run/process/ProcessMutantRunnerTest.scala

The logging for mutations runs began at 0 so we would get awkward scenarios like this:
```
Finished mutation run 15/16 (94%)
Mutation run finished! Took 191 seconds
Total mutants: 16, detected: 16, undetected: 0
```

Fix test runs start from 1 and not use the mutant id's.

---

core/src/test/scala/stryker4s/mutants/findmutants/FileCollectorTest.scala
core/src/test/scala/stryker4s/run/process/ProcessMutantRunnerTest.scala
core/src/test/scala/stryker4s/run/report/ReporterTest.scala
project/Dependencies.scala

I've updated the mockito-scala version and changed some of the usages and imports to `MockitoFixture`, which gives all the needed imports as well as giving each test it's own mock context

Update mockito-scala version

---

core/src/main/scala/stryker4s/mutants/applymutants/MatchBuilder.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala

I've to add some extra tests to make sure the StackOverflow is also prevented.
Fixes #93

Change how pattern matches are being built. This will result in smaller pattern matches.

---

core/src/main/scala/stryker4s/mutants/Mutator.scala
core/src/test/resources/scalaFiles/simpleFile.scala
core/src/test/scala/stryker4s/Stryker4sTest.scala
core/src/test/scala/stryker4s/mutants/MutatorTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
util/src/main/scala/stryker4s/extensions/mutationtypes/StringMutators.scala

This fix changes all interpolated strings to wrap Term.Block statements around it, instead of just around mutated ones. See also #102.  Turns out simple unit tests aren't everything after all. I've added a interpolated test case to the `MutatorTest`, which closer tests the actual result.

Move interpolation fix to Mutator to fix all interpolated strings

---

project/Dependencies.scala

Updates scalameta to 4.1.0. [Includes (among other things) faster parsing](https://github.com/scalameta/scalameta/releases/tag/v4.1.0), which is pretty useful for us.

Update Scalameta to 4.1

---

core/src/main/scala/stryker4s/config/Config.scala
core/src/main/scala/stryker4s/config/implicits/ConfigReaderImplicits.scala
core/src/main/scala/stryker4s/config/implicits/ConfigWriterImplicits.scala
core/src/main/scala/stryker4s/model/MutatedFile.scala
core/src/main/scala/stryker4s/model/MutationsInSource.scala
core/src/main/scala/stryker4s/mutants/Exclusions.scala
core/src/main/scala/stryker4s/mutants/Mutator.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantFinder.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
core/src/main/scala/stryker4s/run/ProcessMutantRunner.scala
core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
core/src/test/scala/stryker4s/config/ConfigTest.scala
core/src/test/scala/stryker4s/mutants/MutatorTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantFinderTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
core/src/test/scala/stryker4s/run/process/ProcessMutantRunnerTest.scala
util/src/main/scala/stryker4s/extensions/exceptions/InvalidExclusionsException.scala

Example of the incorrect logging that happened.
```
INFO  Mutator: 146 Mutant(s) generated.
INFO  Mutator: Of which 142 Mutant(s) are excluded.
INFO  ProcessMutantRunner: Starting test-run 26...
INFO  ProcessMutantRunner: Finished mutation run 26/4 (650%)
INFO  ProcessMutantRunner: Starting test-run 31...
INFO  ProcessMutantRunner: Finished mutation run 31/4 (775%)
```

Fix logging incorrect percentages when mutants are excluded

---

core/src/main/scala/stryker4s/mutants/findmutants/FileCollector.scala
core/src/test/resources/fileTests/filledDir/src/main/scala/package/target.scala
core/src/test/scala/stryker4s/mutants/findmutants/FileCollectorTest.scala

Fixes the bug with a file that is deleted, but not yet staged by git causing a `FileNotFoundException`.
Files that don't exist are now filtered out by the FileCollector

Fix git ls-files bug with non-existent files

---

.travis.yml

REOPEN:
I've added multiple JDK versions to Travis. As now we only test against 1 version on Travis. This should hopefully prevent any problems with different JDK's. As we only use Scala libraries, we probably won't have many problems, but it's still good to test.
I've also added a pre-release version, for us to keep an eye on any problems future JDKs might cause.

Travis multiple jdk versions

---

.github/issue_template.md
.github/pull_request_template.md

This removes the unused info at the top of the GitHub templates. They didn't really add much, and the one in the issue template was formatted wrong so didn't show properly

Remove unused info from github templates

---

build.sbt
core/src/main/scala/stryker4s/Stryker4s.scala
core/src/main/scala/stryker4s/extension/exception/stryker4sException.scala
core/src/main/scala/stryker4s/run/MutantRunner.scala
core/src/main/scala/stryker4s/run/Stryker4sRunner.scala
core/src/main/scala/stryker4s/run/process/ProcessMutantRunner.scala
core/src/test/scala/stryker4s/Stryker4sTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/FileCollectorTest.scala
core/src/test/scala/stryker4s/run/process/ProcessMutantRunnerTest.scala
project/Settings.scala
runners/sbt/src/main/scala/stryker4s/sbt/SbtMutantRunner.scala
runners/sbt/src/main/scala/stryker4s/sbt/Stryker4sPlugin.scala
runners/sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala

I've refactored the sbt plugin a little bit. The `SbtMutantRunner` is little cleaned up, and I've refactored the main settings (everything but the active mutation) to only be calculated once. Unfortunately, they are still applied for each mutation, instead of once, which would be a far larger performance improvement. I've spent some time trying to get that to work, but couldn't (yet).
I've also changed the main `stryker` command to be a `Task`, instead of a `Command`, as recommended by the [sbt documentation](https://www.scala-sbt.org/1.0/docs/Plugins-Best-Practices.html#Use+settings+and+tasks.+Avoid+commands.)

Refactor sbt plugin

---

.travis.yml
README.md
build.sbt
project/Settings.scala
project/plugins.sbt
sonatype.sbt

As there were a couple changes in the Travis.yml with #129, I've used that as a base. That PR should be merged before this one, to get a better diff.
Uses the sbt-ci-release plugin for automated releases from Travis. Every commit on master is now built and uploaded as a snapshot, and tags are built to releases.
Using the sbt-ci-release plugin, I've added another stage to the Travis build. After `Test` is successful, `Release` will start and build, sign and upload a release.

Automated release

---

core/src/main/scala/stryker4s/mutants/Mutator.scala
core/src/test/scala/stryker4s/mutants/MutatorTest.scala
core/src/test/scala/stryker4s/scalatest/FileUtil.scala

Logs when 0 mutants are found, letting the user know something could be wrong with their configuration.
Logging magic 🔮

Log a warning when 0 mutants are found

---

project/Dependencies.scala

This fixes a bug we found and @Wmaarts fixed related to infix syntax printing

Update Scalameta to 4.1.2

---

core/src/main/scala/stryker4s/model/Mutant.scala
core/src/main/scala/stryker4s/model/MutantRunResult.scala
core/src/main/scala/stryker4s/mutants/applymutants/StatementTransformer.scala
core/src/main/scala/stryker4s/mutants/findmutants/FileCollector.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
core/src/main/scala/stryker4s/run/InitialTestRun.scala
core/src/main/scala/stryker4s/run/MutantRunner.scala
core/src/main/scala/stryker4s/run/Stryker4sRunner.scala
core/src/main/scala/stryker4s/run/process/ProcessMutantRunner.scala
core/src/main/scala/stryker4s/run/process/ProcessRunner.scala
core/src/test/scala/stryker4s/Stryker4sTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/StatementTransformerTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/FileCollectorTest.scala
core/src/test/scala/stryker4s/run/process/ProcessMutantRunnerTest.scala
core/src/test/scala/stryker4s/run/process/ProcessRunnerTest.scala
core/src/test/scala/stryker4s/testutil/stubs/TestSourceCollector.scala
runners/command-runner/src/main/scala/stryker4s/run/Stryker4sCommandRunner.scala
runners/sbt/src/main/scala/stryker4s/sbt/SbtMutantRunner.scala
runners/sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala

Ran into some better-code hub warnings while working on the Maven Plugin (#151). Figured it was a bit much to be inside that PR. So I've removed some unused parameters from the `Mutant` case class, removed the `ProcessRunner` from the `MutantRunner`, which is not needed. As well as made the `InitialTestRun` from the `MutantRunner` into its own trait to clean the code up a bit.

Refactor Mutant and MutantRunner

---

core/src/main/scala/stryker4s/model/Mutant.scala
core/src/main/scala/stryker4s/mutants/applymutants/StatementTransformer.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
core/src/test/scala/stryker4s/Stryker4sTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/StatementTransformerTest.scala
core/src/test/scala/stryker4s/run/process/ProcessMutantRunnerTest.scala

It seems I was a bit too enthusiastic with removing code. I removed the mutationType from `Mutant`, not realizing this would still be needed for the HTML reports (and would be nice in the console reporter)

Partial revert of #154 (95dd714), add mutationType back to Mutant

---

core/src/main/scala/stryker4s/mutants/Mutator.scala
core/src/test/scala/stryker4s/mutants/MutatorTest.scala
project/Dependencies.scala

Scalameta 4.1.5 provides some fixes for syntax printing of trees for issues that we ran into.

Update to Scalameta 4.1.5

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

Adds a format-on-save setting for VS Code. And adds a suggested extension of [Metals](https://marketplace.visualstudio.com/items?itemName=scalameta.metals), which is needed for formatting, and acts as a [LSP](https://langserver.org/) for Scala.

Add vscode settings and suggested extensions

---

core/src/main/scala/stryker4s/files/fileIO.scala
core/src/main/scala/stryker4s/report/HtmlReporter.scala
core/src/main/scala/stryker4s/report/Reporter.scala
core/src/test/scala/stryker4s/report/HtmlReporterTest.scala

Writes the html report to file when the HTMLReporter is called. Also added tests.
When this PR is merged, I'd just like to update some documentation and then I think the `feat-html-reporter` branch can be merged to master.
I've also added a `FileIO` trait that abstracts file IO away (duh) for testing purposes. Idea is to later move other file IO (like in the `MutantRunner`) to this trait as well, but that felt a bit out of scope for this PR.

Write HTML report file

---

.travis.yml
project/Release.scala
project/plugins.sbt
runners/maven/pom.xml

Fixes the release build being broken, by it trying to upload a release version to the snapshot repository.
The issue in #186 was that after the maven plugin is deployed, there would be local git changes (pom.xml version was changed). The sbt-sonatype plugin would then think the release was a snapshot, and try to publish that. Versions without `-SNAPSHOT` appended cannot be uploaded to the snapshot repository, so the build would break. 
The mvn goal `versions:revert` is now called after a deploy, reverting any local git changes done, fixing the 
I've also changed the release process to first upload all projects (including the maven plugin) to staging, and then release those when all are completed. This way releasing should be more atomic.

Fix release process

---

core/src/main/scala/stryker4s/extension/TreeExtensions.scala
core/src/main/scala/stryker4s/extension/mutationtype/MutationTypes.scala
core/src/main/scala/stryker4s/extension/mutationtype/StringLiteral.scala
core/src/main/scala/stryker4s/mutants/applymutants/MatchBuilder.scala
core/src/main/scala/stryker4s/mutants/applymutants/StatementTransformer.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
core/src/test/scala/stryker4s/scalatest/TreeEquality.scala
project/Dependencies.scala
project/Settings.scala

The `org.scalameta:contrib` library was only used for two methods. This PR removes the extra dependency

Remove dependency to scalameta contrib

---

.travis.yml

Prevents `mutation-testing-elements` from being re-downloaded each time

Only delete stryker4s dependencies from cache

---

core/src/main/scala/stryker4s/config/ReporterType.scala
core/src/main/scala/stryker4s/model/MutantRunResult.scala
core/src/main/scala/stryker4s/report/HtmlReporter.scala
core/src/main/scala/stryker4s/report/JsonReporter.scala
core/src/main/scala/stryker4s/report/Reporter.scala
core/src/test/scala/stryker4s/report/JsonReporterTest.scala
docs/CONFIGURATION.md

https://github.com/stryker-mutator/stryker4s/issues/208
It add a json output to be parse by bash to send curl to dashboard 
Just add `json` as reporter and a file will be created at 
```
config.baseDir / s"target/stryker4s-result-${System.currentTimeMillis()}" / "result.json"
```
The file will contains `mutationScore` and `durationSeconds`.

Add a Json reporter

---

core/src/main/scala/stryker4s/config/Config.scala
core/src/test/resources/fileTests/filledDir/src/main/scala/fileInRootSourceDir.scala
core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
core/src/test/scala/stryker4s/config/ConfigTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/FileCollectorTest.scala

Fixes the collection of files to be mutated so that files located in the root Scala source directory are taken into account as well, not just those in sub directories.
Changes the glob pattern for collection files to be mutated so that files in the root Scala source directory are matching as well.

Make sure files in root of Scala source directory get mutated

---

core/src/main/scala/stryker4s/mutants/applymutants/MatchBuilder.scala
core/src/test/scala/stryker4s/mutants/MutatorTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala

Fixes the scenario where a user has the variable `sys` would conflict with generated code and cause a compile error.
Thansk to @dwestheide's suggestion! Generated code now uses `_root_.scala.sys.env.get(...)` instead of `sys.env.get(...)`

Fix possible conflict with generated code in user's variable names

---

.travis.yml
project/Settings.scala
project/plugins.sbt

It's not used much (I never check it) and only slows down the build

Remove sbt-scoverage

---

.github/workflows/ci.yml
runners/sbt/src/sbt-test/sbt-stryker4s/test-1/src/test/scala/example/ExampleTest.scala
runners/sbt/src/sbt-test/sbt-stryker4s/test-1/stryker4s.conf

Fixes the sbt scripted tests to run on ci again
Apparently the coursier-based launcher is a bit more finnicky with how scripted tests should be run. So the command is now changed to something more specific.

Fix sbt scripted tests not running in CI

---

core/src/main/scala/stryker4s/report/dashboard/Providers.scala
core/src/test/scala/stryker4s/report/dashboard/DashboardConfigProviderTest.scala

GitHub actions is now supported by the dashboard upload
Adds a new CI provider: GitHub actions

Add GitHub actions dashboard CI provider

---

core/src/main/scala/stryker4s/config/Config.scala
core/src/main/scala/stryker4s/report/Reporter.scala
core/src/test/resources/stryker4sconfs/duplicateKeys.conf
core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
core/src/test/scala/stryker4s/config/ConfigTest.scala
core/src/test/scala/stryker4s/report/ReporterTest.scala

Reporters could be duplicate, causing them to be called twice. Now it is a `Set`, so each reporter is unique

Filter out duplicate reporters in config

---

core/src/main/scala/stryker4s/report/ConsoleReporter.scala
core/src/main/scala/stryker4s/report/DashboardReporter.scala
core/src/main/scala/stryker4s/report/HtmlReporter.scala
core/src/main/scala/stryker4s/report/JsonReporter.scala
core/src/main/scala/stryker4s/report/MutationRunReporter.scala
core/src/main/scala/stryker4s/report/Reporter.scala
core/src/main/scala/stryker4s/run/MutantRunner.scala
core/src/test/scala/stryker4s/Stryker4sTest.scala
core/src/test/scala/stryker4s/report/ConsoleReporterTest.scala
core/src/test/scala/stryker4s/report/ConsoleReporterTypeTest.scala
core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
core/src/test/scala/stryker4s/report/HtmlReporterTest.scala
core/src/test/scala/stryker4s/report/JsonReporterTest.scala
core/src/test/scala/stryker4s/report/ReporterTest.scala

With the mutation testing dependency, some regressions were introduced:
This PR changes that back

Revert reporter regressions

---

runners/sbt/src/main/scala/stryker4s/sbt/runner/SbtMutantRunner.scala

Reverts stryker-mutator/stryker4s#392
Unfortunately, this creates a memory leak when sbt keeps running, slowing down each test run more and more. When running on stryker4s, the mutation run would stall around 50%.

Revert "perf(sbt): don't fork every test-run"

---

core/src/test/scala/stryker4s/testutil/Stryker4sSuite.scala
runners/maven/src/test/scala/stryker4s/testutil/Stryker4sSuite.scala

Changes the base ScalaTest Stryker4sSuite to an abstract class, as [recommended by ScalaTest](http://www.scalatest.org/user_guide/defining_base_classes)

Change Stryker4sSuite to abstract class

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Adds [VS Code devcontainers](https://code.visualstudio.com/docs/remote/containers) setup. It allows all development to be done inside a Docker container with a VS Code 'server' component running. This should make it easier for new contributors to get started, as all they need is to have VS Code and Docker installed

Setup VS Code devcontainer

---

.github/workflows/ci.yml
.github/workflows/mutation-testing.yml
build.sbt
maven/README.MD
project/Dependencies.scala
project/Release.scala
project/Settings.scala
project/plugins.sbt

Adds [sbt-projectmatrix](https://github.com/sbt/sbt-projectmatrix/) to the build. This has two main benefits:
- Each scalaVersion can be compiled in parallel for each project, speeding up the build
- When developing, the 'main' scalaVersion can now be 2.13, which is faster to compile (and thus develop on)

Add sbt-projectmatrix 

---

sbt/src/main/scala/stryker4s/sbt/runner/SbtMutantRunner.scala

Adds some scalacOptions that are the same as on 2.12, but for 2.13

Filter out scalacOptions that can break on Scala 2.13 projects

---

core/src/main/scala/stryker4s/config/Config.scala
core/src/main/scala/stryker4s/config/TestFilter.scala
core/src/test/scala/stryker4s/config/ConfigTest.scala
core/src/test/scala/stryker4s/config/TestFilterTest.scala
docs/CONFIGURATION.md
sbt/src/main/scala/stryker4s/sbt/runner/SbtMutantRunner.scala
sbt/src/sbt-test/sbt-stryker4s/test-1/src/test/scala/example/IgnoreMeTest.scala
sbt/src/sbt-test/sbt-stryker4s/test-1/stryker4s.conf

Adds `test-filter` to `Config`
It restricts the tests that are run for every mutation, so that we can ignore heavy `integration` tests and focus on `unit` ones

Add test-filter to Config

---

core/src/main/scala/stryker4s/extension/TreeExtensions.scala
core/src/test/scala/stryker4s/extension/TreeExtensionsTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala

The MatchBuilder replaces any nodes by folding a list of statements to be mutated. It finds the node to be replaced in an AST and replaces it with a new node (the mutation). If a node has already been replaced, the builder can't find the node and won't replaced it. That means the mutation is never properly activated, resulting in an always Survived mutant.
This happens when there is a mutation in a statement that and the result that it is pattern-matched on.
Count a pattern match as a top-statement so they'll always be mutated together and not skipped

fix: include pattern-matches in topStatements

---

core/src/main/scala/stryker4s/extension/TreeExtensions.scala
core/src/main/scala/stryker4s/mutants/applymutants/MatchBuilder.scala
core/src/test/scala/stryker4s/extension/TreeExtensionsTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala

A slightly more thorough fix. If mutations can't be added, they are now logged so the user can report the issue.
Also reworks the topStatement logic to work the other way around. Going up until we know for sure the parent is of a type that contains 'top-statements' (such as blocks, statements in ifs, etc). This should be more robust.
Logging is added to the MatchBuilder, and the topStatement function is rewritten slightly.

Rework topStatement logic and log if mutations aren't added

---

core/src/main/scala/stryker4s/extension/TreeExtensions.scala
core/src/test/scala/stryker4s/extension/TreeExtensionsTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala

Previously the whole try-catch would be included in a topStatement. This PR fixes that to stop at the `case` statement, so it will be included in the build pattern match.

Fix catch-statements not being included in mutations

---

README.md
core/src/main/scala/stryker4s/extension/TreeExtensions.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantFinderTest.scala

Use @SuppressWarnings annotation to skip mutations
This PR allow skip particular mutations in annotated context. For example if we dont need mutate exact line of code (like constant value)
It will iterate to root of syntax Tree checking for @SuppressWarnings annotation. If this annotation contains id of mutation (for example `@SuppressWarnings(Array("stryker4s.extension.mutationtype.StringLiteral))`), then this mutation will be skipped

Fixes stryker-mutator/stryker4s#495

---

sbt/src/main/scala/stryker4s/sbt/Stryker4sMain.scala
sbt/src/sbt-test/sbt-stryker4s/test-1/build.sbt
sbt/src/sbt-test/sbt-stryker4s/test-1/project/build.properties
sbt/src/sbt-test/sbt-stryker4s/test-1/stryker4s.conf

Adds a check before running Stryker4s if the current version is supported. Uses direct string comparison, so might be a little iffy in some cases. Though it worked in most I tested

Add minimum supported version to sbt plugin

---

sbt/src/main/scala/stryker4s/sbt/runner/SbtMutantRunner.scala

Sbt can report test 'error's. ScalaTest reports this when a test class is unable to initialize. We should report this as a failed test-run, not an error. Resulting as an error will mark the mutant as `CompileError` which is wrong.
This change can result in a slightly different mutation score.

Report sbt Error TestResult correctly as failed instead of error

---

core/src/main/scala/stryker4s/report/ConsoleReporter.scala
core/src/test/scala/stryker4s/report/ConsoleReporterTest.scala

The metrics report score can be a NaN when there are no survived mutants. We should be able to handle that.

Handle NaN mutation score in report correctly

---

command-runner/src/test/scala/stryker4s/run/ProcessMutantRunnerTest.scala
core/src/main/scala/stryker4s/env/package.scala
core/src/main/scala/stryker4s/report/AggregateReporter.scala
core/src/main/scala/stryker4s/report/dashboard/DashboardConfigProvider.scala
core/src/main/scala/stryker4s/report/dashboard/Providers.scala
core/src/main/scala/stryker4s/report/package.scala
core/src/main/scala/stryker4s/run/Stryker4sRunner.scala
core/src/test/scala/stryker4s/Stryker4sTest.scala
core/src/test/scala/stryker4s/report/ReporterTest.scala

Renames `Reporter` to `AggregateReporter`, add a new type alias `Reporter` that combines both reporter types and inject the configured reporters into the `AggregateReporter` instead of creating them on initialization of the class

Inject reporters into (renamed) AggregateReporter

---

maven/README.MD
maven/src/main/scala/stryker4s/maven/runner/MavenMutantRunner.scala
maven/src/test/scala/stryker4s/maven/runner/MavenMutantRunnerTest.scala

Propagate active profiles from stryker4s maven plugin configuration to stryker runs, which allows to change different settings specifically for stryker4s runs

Propagate active profiles from Maven plugin configuration to stryker runs

---

core/src/main/scala/stryker4s/extension/TreeExtensions.scala
core/src/test/scala/stryker4s/extension/TreeExtensionsTest.scala

With the statement `def foo = bar(baz = true)` the `topStatement` of `true` would be `baz = true` which creates incorrect mutated code that doesn't compile. It is now just `true`.

Fix topStatement for argument Assign terms

---

core/src/main/scala/stryker4s/extension/TreeExtensions.scala
core/src/main/scala/stryker4s/extension/mutationtype/StringLiteral.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
core/src/test/scala/stryker4s/extension/TreeExtensionsTest.scala
core/src/test/scala/stryker4s/mutants/AddAllMutationsTest.scala
core/src/test/scala/stryker4s/mutants/MutatorTest.scala
core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala

Mutations in `case` statements were not always added to mutated code. It is now 🎉
Changes in `topStatement` so it will stop at the body of a case instead of stopping at the `topStatement` of the case itself

Fix mutations in `case` statements not always being added

---

.github/workflows/mutation-testing.yml
command-runner/src/test/scala/stryker4s/run/ProcessMutantRunnerTest.scala
core/src/main/scala/stryker4s/extension/ResourceExtensions.scala
core/src/main/scala/stryker4s/run/TestRunner.scala
core/src/test/scala/stryker4s/Stryker4sTest.scala
core/src/test/scala/stryker4s/extension/CatsEffectExtensionsTest.scala
core/src/test/scala/stryker4s/extension/ResourceExtensionsTest.scala
core/src/test/scala/stryker4s/report/ConsoleReporterTest.scala
core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
core/src/test/scala/stryker4s/report/HtmlReporterTest.scala
core/src/test/scala/stryker4s/report/JsonReporterTest.scala
core/src/test/scala/stryker4s/report/ReporterTest.scala
core/src/test/scala/stryker4s/testutil/MockitoSuite.scala
core/src/test/scala/stryker4s/testutil/Stryker4sSuite.scala
project/Dependencies.scala
project/Settings.scala

Sets up easier testing with cats-effect. Calling `.unsafeRunSync` is no longer required, and a test that returns an `IO` that is not an `IO[Assertion]` will cause a compile error

Set up cats-effect-testing-scalatest

---

core/src/main/scala/stryker4s/report/HtmlReporter.scala
core/src/test/scala/stryker4s/report/HtmlReporterTest.scala

When you change the theme of the HTML report, the background of the parent HTML page changes also.
The HTML report component dispatches a theme-changed event when the theme has changed. This solution listens for that event and changes the background of the body accordingly.

HTML report body changes with theme

---

command-runner/src/test/scala/stryker4s/run/ProcessMutantRunnerTest.scala
core/src/test/scala/stryker4s/Stryker4sTest.scala
core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
core/src/test/scala/stryker4s/report/HtmlReporterTest.scala
core/src/test/scala/stryker4s/report/JsonReporterTest.scala
core/src/test/scala/stryker4s/report/ReporterTest.scala
core/src/test/scala/stryker4s/testutil/MockitoSuite.scala
core/src/test/scala/stryker4s/testutil/Stryker4sSuite.scala
project/Dependencies.scala
project/Settings.scala

AsyncIOSpec from cats-effect-testing overrides the implicit executioncontext from ScalaTests single-threaded one. This means that multiple tests in the same suite are started concurrently. This doesn't really provide a speed benefit, but it does mean that Mockito-Scala will complain about mocks from other tests that aren't disposed properly (because they are still running).

Use ScalaTests ExecutionContext when running AsyncSpec

---

docs/sidebar.json

As discussed, this will be used to render the sidebar on the website.
The `sidebar.json` (or `sidebar.js` if you prefer a node module) should contain a valid [sidebar object](https://v2.docusaurus.io/docs/docs-introduction#sidebar-object). The document root is `stryker4s`, so [document ids](https://v2.docusaurus.io/docs/docs-introduction#document-id) should be prefixed with that.

 docs(sidebar): add custom sidebar

---

.scalafmt.conf
core/src/main/scala/stryker4s/config/Config.scala
core/src/main/scala/stryker4s/config/implicits/ConfigReaderImplicits.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantFinder.scala
core/src/test/resources/scalaFiles/scala3File.scala
core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantFinderTest.scala
core/src/test/scala/stryker4s/testutil/ExampleConfigs.scala
docs/configuration.md

Adds support for Scala 3 syntax by adding a configurable scala dialect parsing configuration.
Passes the configured dialect to Scalameta. Default is Scala 3 because most syntax is backwards compatible

Support Scala 3 syntax with configurable scala-dialect

---

command-runner/src/main/scala/stryker4s/command/runner/ProcessTestRunner.scala
core/src/main/scala/stryker4s/run/process/ProcessRunner.scala
core/src/main/scala/stryker4s/run/process/WindowsProcessRunner.scala
core/src/test/scala/stryker4s/testutil/stubs/TestProcessRunner.scala

In a regression since 0.10.0, the command-runner would set the `"ACTIVE_MUTATION"` environment variable to `"NONE"`, which would then try to be parsed to a Int. This of course throws an exception, which fails the initial test-run. 
With this PR the environment variable is not set, which makes the mutation switch go to the default case

Fix NumberFormatException for command-runner

---

.github/workflows/ci.yml
core/src/main/scala/stryker4s/report/AggregateReporter.scala
core/src/main/scala/stryker4s/report/DashboardReporter.scala
core/src/main/scala/stryker4s/run/Stryker4sRunner.scala
core/src/test/scala/stryker4s/report/AggregateReporterTest.scala
core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
docs/configuration.md
project/Dependencies.scala
project/Settings.scala

Replaces the [sttp](https://github.com/softwaremill/sttp#readme) backend from [async-http-client](https://sttp.softwaremill.com/en/latest/backends/catseffect.html#cats-effect-backend) to [HttpClient](https://sttp.softwaremill.com/en/latest/backends/fs2.html#using-httpclient-java-11). This means the dashboard reporter will only work on Java 11 or higher. The upside is that Netty is no longer a transitive dependency. An error is logged and thrown when Java <11 tries to use the dashboard reporter.
Also moves around some reporting logic to have the HttpClient only initialize when sending the report, instead of initializing it when starting Stryker4s and keeping it alive the whole time. `FinishedRunReporter`s that throw an error will now also make Stryker4s fail instead of just logging a …

Replace sttp async-http-client backend with httpclient (Java 11+)

---

core/src/main/scala/stryker4s/extension/PartialFunctionOps.scala
core/src/main/scala/stryker4s/extension/mutationtype/MutationTypes.scala
core/src/main/scala/stryker4s/extension/mutationtype/RegexMutator.scala
core/src/main/scala/stryker4s/model/IgnoredMutationReason.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantFinder.scala
core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
core/src/test/scala/stryker4s/extension/PartialFunctionOpsTest.scala
core/src/test/scala/stryker4s/mutants/AddAllMutationsTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantFinderTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
project/Dependencies.scala
project/Settings.scala

Implements weapon-regex to mutate regular expressions. Can recognize regular expressions on 3 patterns:
```scala
// Option 1: Scala regex constructor
def regex1 = new Regex("[a-z]")
def regex1 = new scala.util.matching.Regex("[a-z]")
// Option 2: Java regex constructor
def regex2 = Pattern.compile("[a-z]")
def regex2 = java.util.regex.Pattern.compile("[a-z]")
// Option 3: `.r` op on String
def regex3 = "[a-z]".r
```
For now, only regex level 1 is enabled. Once we agree on what levels mean what for mutation testing we can add more fine-grained control over regular expression mutators.

Mutate regular expressions using weapon-regex

---

core/src/main/scala/stryker4s/extension/mutationtype/StringLiteral.scala
core/src/test/scala/stryker4s/extension/mutationtype/MutationTypesTest.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala

Pattern interpolation would be matched and mutated, even if it would create compile errors:
```scala
a match {
case q"foo.bar" => _
}
```
Would be mutated to:
```scala
a match {
case q"" => _
}
```
And create a compile error. This PR fixes string mutators matching on Pattern interpolation

Fix pattern interpolation matching on string mutations

---

core/src/main/scala/stryker4s/config/Config.scala
core/src/test/scala/stryker4s/config/ConfigTest.scala
docs/configuration.md

From testing, something around a little above 1/4th seems to give the best performance.

Edit default concurrency algorithm to be more conservative

---

sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala
sbt/src/sbt-test/sbt-stryker4s/test-1/build.sbt

Fixes #726
Sbt has two settings to control where source code is: one for Java and one for Scala (`javaSource` and `scalaSource` respectively). In some cases, like in Play Framework, both of those settings point to the same directory:
https://github.com/playframework/playframework/blob/c5a0193afe2069fd16feba29960638609bd2eaa8/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayLayoutPlugin.scala#L30-L31
This means that when Stryker4s sets the `scalaSource` to the new directory with mutated code, the `javaSource` still points to the old directory, giving sbt two directories with the same filenames and code (one mutated, one not mutated).
This PR fixes this by setting the `javaSource` to the new directory that Stryker4s created. For Play Framework, this works because both source settings now …

Fix [SomeClass] is already defined as [SomeClass]

---

core/src/main/scala/stryker4s/config/pure/ConfigConfigReader.scala

Prevents `'other' is different type of Path` exception when defining a base-dir

Always read base-dir config as absolute path

---

core/src/main/scala/stryker4s/extension/mutationtype/StringLiteral.scala
core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala

XML literals are no longer mutated. Fixes a bug where xml literals would be mutated, resulting in invalid code.
The string literal mutator now checks if it is not part of a xml literal. Mutations interpolated inside xml literals still mutate:
```scala
val p = <p>${"foo"}</p> // Mutates "foo"
val h1 = <h1>foo</h1> // No mutations
```

Don't mutate xml literals

---

command-runner/src/main/scala/stryker4s/command/runner/ProcessTestRunner.scala
command-runner/src/test/scala/stryker4s/run/ProcessTestRunnerTest.scala
core/src/main/scala/stryker4s/config/Config.scala
core/src/main/scala/stryker4s/config/DebugOptions.scala
core/src/main/scala/stryker4s/config/circe/ConfigEncoder.scala
core/src/main/scala/stryker4s/run/Stryker4sRunner.scala
core/src/main/scala/stryker4s/run/process/ProcessResource.scala
core/src/main/scala/stryker4s/run/process/ProcessRunner.scala
core/src/main/scala/stryker4s/run/process/WindowsProcessRunner.scala
core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
core/src/test/scala/stryker4s/config/circe/ConfigEncoderTest.scala
core/src/test/scala/stryker4s/testutil/ExampleConfigs.scala
core/src/test/scala/stryker4s/testutil/stubs/TestProcessRunner.scala
docs/configuration.md
sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala
sbt/src/main/scala/stryker4s/sbt/runner/ProcessTestRunner.scala

Adds two new options in a `debug` config field:
- `debug.log-test-runner-stdout`: stdout from the testrunner is no longer logged to debug by default, but only when this option is enabled
- `debug.debug-test-runner`: Limit concurrency to 1 and adds JVM debug arguments to the testrunner so debuggers can attach to it

Add debug configuration options

---

project/Settings.scala

Running Stryker4s on Stryker4s locally would give version evict errors.

Setup libraryDependencySchemes for stryker4s dependencies

---

api/src/main/protobuf/stryker4s/api/testprocess.proto
api/src/main/scala/stryker4s/api/testprocess/CoverageReport.scala
command-runner/src/main/scala/stryker4s/command/runner/ProcessTestRunner.scala
core/src/main/scala/stryker4s/run/MutantRunner.scala
core/src/main/scala/stryker4s/run/TestRunner.scala
core/src/test/scala/stryker4s/run/TestRunnerTest.scala
core/src/test/scala/stryker4s/testutil/stubs/TestRunnerStub.scala
maven/src/main/scala/stryker4s/maven/runner/MavenTestRunner.scala
maven/src/test/scala/stryker4s/maven/runner/MavenTestRunnerTest.scala
sbt-testrunner/src/main/scala/stryker4s/package.scala
sbt-testrunner/src/main/scala/stryker4s/sbt/testrunner/MessageHandler.scala
sbt-testrunner/src/main/scala/stryker4s/sbt/testrunner/TestInterfaceMapper.scala
sbt-testrunner/src/main/scala/stryker4s/sbt/testrunner/TestRunner.scala
sbt/src/main/scala/stryker4s/sbt/runner/LegacySbtTestRunner.scala
sbt/src/main/scala/stryker4s/sbt/runner/ProcessTestRunner.scala

When implementing #1001, we looked at `Fingerprint`s to filter on tests. The misinterpretation with this was that `Fingerprint`s only have information about the _test framework_ that the test is running under, and not the test information. The message for starting a test would look like:
```scala
StartTestRun(1, Vector(Fingerprint("org.scalatest.Suite"), Fingerprint("org.scalatest.Suite"), Fingerprint("org.scalatest.Suite"))
```
This PR fixes that to always look at the `fullyQualifiedName` from a `TaskDef` instead. The message now properly has desired test coverage in it: 
```scala
StartTestRun(1, Vector("stryker4s.config.ConfigTest", "stryker4s.config.ConfigReaderTest", "stryker4s.files.GlobTest"))
```
for example.
As a result of this fix, the average tests run per mutant has gone from …

Fix per-test coverage analysis

---

sbt-testrunner/src/main/scala/stryker4s/package.scala

By only adding a covered test once, instead of each time it is hit. Makes the protobuf messages smaller and lowers the memory usage in the initial test-run

Optimize CoverageTestRunResult size

---

api/src/main/protobuf/stryker4s/api/testprocess.proto
sbt-testrunner/src/main/scala/stryker4s/package.scala
sbt-testrunner/src/main/scala/stryker4s/sbt/testrunner/MessageHandler.scala
sbt/src/main/scala/stryker4s/sbt/runner/ProcessTestRunner.scala

Calculate the duration of the initial test-run without framework overhead.

Use more accurate initial test-run duration (sbt plugin)

---

core/src/main/scala/stryker4s/mutants/findmutants/MutantFinder.scala
sbt/src/main/scala/stryker4s/sbt/Stryker4sMain.scala
sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala
sbt/src/main/scala/stryker4s/sbt/runner/ProcessTestRunner.scala
sbt/src/main/scala/stryker4s/sbt/runner/SbtTestRunner.scala
sbt/src/main/scala/stryker4s/sbt/runner/TestRunnerConnection.scala

Usage of the older java.net network stuff is discouraged as it is less performant and uses blocking code. Fs2 thankfully has some nice interfaces for sockets built on NIO2

Use fs2 socket implementations instead of old java.net

---

core/src/main/scala/stryker4s/report/mapper/MutantRunResultMapper.scala
core/src/test/scala/stryker4s/report/mapper/MutantRunResultMapperTest.scala

Adds more info to the mutation testing report. Adds system info (cpu, ram, etc), and branding info (framework name, logo, etc)

Fill report with system and framework info

---

build.sbt

This is useful when running local tests for stryker4s-command-runner.
Make publishPluginLocal also publish stryker4s-command-runner for Scala 2.12 and 2.13.

sbt: enable local publish for stryker4s-command-runner

---

core/src/main/scala/stryker4s/env/package.scala
core/src/main/scala/stryker4s/report/DashboardReporter.scala
core/src/main/scala/stryker4s/report/dashboard/DashboardConfigProvider.scala
core/src/main/scala/stryker4s/report/dashboard/Providers.scala
core/src/main/scala/stryker4s/run/Stryker4sRunner.scala
core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
core/src/test/scala/stryker4s/report/dashboard/DashboardConfigProviderTest.scala

Refactors env loading for the dashboard to use cats-effect Env typeclass instead of `sys.env` with a `Map[String, String]`. This simplifies some of the code, and makes testing a bit easier. 
The `Env` typeclass provides a different way to reading environment variables than `sys.env`, mainly the `.get` returns an effect because the environment is not 'pure'. The `DashboardConfigProvider` and `CIProvider` now use the `Env` typeclass, and a `F[_]` type parameter to allow for different effect types. Runtime code uses `IO`, and tests use `Id` (which is an alias for no suspension).
https://typelevel.org/cats-effect/docs/std/env

Use cats-effect Env for reading CI environment variables

---

sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala

For helping debug an issue on Scala 3.3.1 / sbt 1.9.6
```
[info] set current project to fakeRoot (in build file:/home/fabian/Development/LibreCybernetics/basecodecs.scala/)
[warn] No test frameworks found via sbt / loadedTestFrameworks
[info] Creating 7 test-runners
```

[sbt] Add warning in case of empty framework sequence

---

modules/sbt/src/main/scala/stryker4s/sbt/Stryker4sPlugin.scala
modules/sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala

Fixes #646
Also fixes some issue where _most_ source code was mutated, rather than _all_, if the project had multiple source directories.

fix: compatibility with sbt-crossproject

---

modules/core/src/main/scala/stryker4s/config/source/CliConfigSource.scala
modules/core/src/test/scala/stryker4s/config/source/CliConfigSourceTest.scala
project/Dependencies.scala
project/Settings.scala

Fixes #1737
Replaces Decline with Opt. Unfortunately Decline does not allow unhandled arguments, which we need for the way we parse configuration. Scopt does allow this. The API for the CLI remains the same.

fix(CLI): correctly parse multiple CLI arguments

---

modules/sbt/src/main/scala/stryker4s/sbt/Stryker4sPlugin.scala
modules/sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala
modules/sbt/src/main/scala/stryker4s/sbt/runner/ProcessTestRunner.scala
modules/sbt/src/main/scala/stryker4s/sbt/runner/SbtTestRunner.scala

Fixes #1740
Create a temporary arg file for java arguments. The file is removed after the process is closed.
Also start the process with javaHome from sbt, if set

fix(sbt): use argfile to start new java processes

---

modules/sbtTestRunner/src/main/scala/stryker4s/sbt/testrunner/TestRunner.scala

fix(testrunner): fix null pointer exception in testrunner when event throwable is null
