stryker-mutator/stryker4s

- .travis.yml
- build.sbt
- project/Dependencies.scala
- project/Settings.scala
- util/src/test/scala/stryker4s/scalatest/TreeEquality.scala
Fixes #1.
Runs a commit with scala 2.12.6. The [default test script for travis sbt projects](https://docs.travis-ci.com/user/languages/scala/#sbt-Default-Script-Command) is `sbt test`, so no further script commands are needed as of yet
> Add .travis.yml file

- README.md
- docs/CONFIGURATION.md
- docs/MUTATORS.md
Fixes #3 
I've added some documentation for what this project is, it's current status, as well as documentation for configuration options and supported mutators
> Improve documentation (readme, supported mutators & configuration)

- .github/ISSUE_TEMPLATE/issue_template.md
Added a generic issue template that could be used to file bug reports.
> Update issue templates

- util/src/main/scala/stryker4s/extensions/ImplicitMutationConversion.scala
- util/src/main/scala/stryker4s/extensions/mutationtypes/MutationTypes.scala
Fixes #27 
`sbt doc` now completes succesfully
> Fix scaladox

- README.md
> Add a badge for gitter

- README.md
- docs/CONTRIBUTING.md
> Add contributing guide

- util/src/main/scala/stryker4s/extensions/mutationtypes/LogicalOperators.scala
Small change -- self explanatory
> or/and should be LogicalOperator instead of BinaryOperator

- docs/MUTATORS.md
> Escaping the vertical bars

- docs/CONFIGURATION.md
log-level information was all on one line. This fixes that
> Fix enters in configuration md

- sbt/src/main/scala/stryker4s/sbt/SbtMutantRunner.scala
Now it uses the same directory configured in the project.
> Fix the way Runner calculates scalaSources for main and test sources.

- core/src/main/scala/stryker4s/mutants/findmutants/FileCollector.scala
- core/src/main/scala/stryker4s/run/MutantRunner.scala
- sbt/src/main/scala/stryker4s/sbt/SbtMutantRunner.scala
Now Stryker works directly as a plugin and through `scripted` command
> Sbt plugin

- core/src/main/scala/stryker4s/config/Config.scala
- core/src/main/scala/stryker4s/config/ConfigReader.scala
- core/src/main/scala/stryker4s/config/implicits/ConfigReaderImplicits.scala
- core/src/main/scala/stryker4s/config/implicits/ConfigWriterImplicits.scala
- core/src/main/scala/stryker4s/model/Exclusions.scala
- core/src/main/scala/stryker4s/model/Mutant.scala
- core/src/main/scala/stryker4s/model/MutatedFile.scala
- core/src/main/scala/stryker4s/model/MutationsInSource.scala
- core/src/main/scala/stryker4s/mutants/Exclusions.scala
- core/src/main/scala/stryker4s/mutants/Mutator.scala
- core/src/main/scala/stryker4s/mutants/applymutants/StatementTransformer.scala
- core/src/main/scala/stryker4s/mutants/findmutants/MutantFinder.scala
- core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
- core/src/main/scala/stryker4s/run/ProcessMutantRunner.scala
- core/src/test/resources/stryker4sconfs/filled.conf
- core/src/test/scala/stryker4s/Stryker4sTest.scala
- core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
- core/src/test/scala/stryker4s/config/ConfigTest.scala
- core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
- core/src/test/scala/stryker4s/mutants/applymutants/StatementTransformerTest.scala
- core/src/test/scala/stryker4s/mutants/findmutants/MutantFinderTest.scala
- core/src/test/scala/stryker4s/run/process/ProcessMutantRunnerTest.scala
- docs/CONFIGURATION.md
- stryker4s.conf
- util/src/main/scala/stryker4s/extensions/mutationtypes/MutationTypes.scala
In the spirit of hacktoberfest, this fixes #4 . This is my first PR to this repo so any feedback at all is more than welcome.
> Disable mutations

- core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
- core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
- util/src/main/scala/stryker4s/extensions/mutationtypes/ArgMethodExpression.scala
> Fix forAll mutator to forall

- core/src/main/scala/stryker4s/extension/mutationtype/ArgMethodExpression.scala
- core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
- core/src/test/scala/stryker4s/extension/mutationtype/MethodExpressionTest.scala
- core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
I've added mutators for `takeRight` -> `dropRight` (and other way around), and `takeWhile` -> `dropWhile` (and other way around).
Mutator magic 🔮
> Add takeRight, dropRight, takeWhile, dropWhile mutators

- core/src/main/scala/stryker4s/config/Config.scala
- core/src/main/scala/stryker4s/config/ReporterType.scala
- core/src/main/scala/stryker4s/config/implicits/ConfigReaderImplicits.scala
- core/src/main/scala/stryker4s/config/implicits/ConfigWriterImplicits.scala
- core/src/main/scala/stryker4s/files/fileIO.scala
- core/src/main/scala/stryker4s/report/HtmlReporter.scala
- core/src/main/scala/stryker4s/report/Reporter.scala
- core/src/main/scala/stryker4s/report/mapper/MutantRunResultMapper.scala
- core/src/main/scala/stryker4s/report/model/mutationTestReport.scala
- core/src/test/resources/mutation-testing-report-schema.json
- core/src/test/resources/stryker4sconfs/filled.conf
- core/src/test/scala/stryker4s/Stryker4sTest.scala
- core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
- core/src/test/scala/stryker4s/report/ConsoleReporterTypeTest.scala
- core/src/test/scala/stryker4s/report/HtmlReporterTest.scala
- core/src/test/scala/stryker4s/report/mapper/MutantRunResultMapperTest.scala
- core/src/test/scala/stryker4s/report/model/MutationTestResultTest.scala
- core/src/test/scala/stryker4s/testutil/MutationTestingElementsJsonSchema.scala
- docs/CONFIGURATION.md
- project/Dependencies.scala
- project/Settings.scala
Adds support for the new HTML reporter. 
Most of the code has already been reviewed in other PR's to this branch, but it might be nice to have a final look.
> Feat html reporter

- core/src/main/scala/stryker4s/config/Config.scala
- core/src/test/resources/stryker4sconfs/filled.conf
- core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
- core/src/test/scala/stryker4s/config/ConfigTest.scala
- docs/CONFIGURATION.md
Why waste our beautiful HTML reporter to not be enabled by default?
> Enable html reporter by default

- core/src/test/scala/stryker4s/Stryker4sTest.scala
- core/src/test/scala/stryker4s/mutants/findmutants/FileCollectorTest.scala
- core/src/test/scala/stryker4s/report/HtmlReporterTest.scala
- core/src/test/scala/stryker4s/report/ReporterTest.scala
- core/src/test/scala/stryker4s/scalatest/LogMatchers.scala
- core/src/test/scala/stryker4s/testutil/MockitoSuite.scala
- core/src/test/scala/stryker4s/testutil/Stryker4sSuite.scala
- project/Dependencies.scala
- runners/command-runner/src/test/scala/stryker4s/run/ProcessMutantRunnerTest.scala
- runners/maven/pom.xml
- runners/maven/src/test/scala/stryker4s/maven/MavenMutantRunnerTest.scala
- runners/maven/src/test/scala/stryker4s/testutil/Stryker4sSuite.scala
Mockito trait is now defined and a single import. Small changes in some mocks.
> Unify mockito scala usage

- core/src/main/scala/stryker4s/report/model/mutationTestReport.scala
- core/src/test/scala/stryker4s/Stryker4sTest.scala
- core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
- core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
- core/src/test/scala/stryker4s/run/threshold/ThresholdCheckerTest.scala
- core/src/test/scala/stryker4s/testutil/stubs/TestSourceCollector.scala
- project/Settings.scala
- runners/command-runner/src/test/scala/stryker4s/config/ProcessConfigReaderTest.scala
Adds some new stricter compile options
> New compiler options

- core/src/main/scala/stryker4s/config/ReporterType.scala
- core/src/main/scala/stryker4s/config/implicits/ConfigReaderImplicits.scala
- core/src/main/scala/stryker4s/http/webIO.scala
- core/src/main/scala/stryker4s/report/DashboardReporter.scala
- core/src/main/scala/stryker4s/report/Reporter.scala
- core/src/main/scala/stryker4s/report/dashboard/Providers.scala
- core/src/main/scala/stryker4s/report/model/StrykerDashboardReport.scala
- core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
- core/src/test/scala/stryker4s/report/JsonReporterTest.scala
- core/src/test/scala/stryker4s/report/ReporterTest.scala
- docs/CONFIGURATION.md
- project/Dependencies.scala
- project/Settings.scala
Add a dashboard reporter
hit the dashboard api reporter URL and post the results when test is completed
> Add Dashboard reporter

- core/src/main/scala/stryker4s/report/DashboardReporter.scala
- core/src/main/scala/stryker4s/report/dashboard/Providers.scala
- core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
Dashboard reporter should now work
- Prepend `github.com/` to repositorySlug
- Always check for 201 instead of 2xx
- Fix and add to tests
> Fix dashboard reporter

- .travis.yml
- project/Dependencies.scala
- runners/maven/pom.xml
- runners/sbt/src/sbt-test/sbt-stryker4s/test-1/build.sbt
[Faster compile times? Yes please](https://github.com/scala/scala/releases/tag/v2.12.9)
> Update scala to 2.12.9

- .github/workflows/mutation-testing.yml
- runners/sbt/src/main/scala/stryker4s/sbt/runner/SbtMutantRunner.scala
> Blacklist scalacOptions that can cause errors

- runners/sbt/src/main/scala/stryker4s/sbt/runner/SbtMutantRunner.scala
Improves the performance of the stryker4s sbt plugin by quite a bit. Previously, `fork := true` was always set by stryker4s, meaning that for every test run a new JVM was started. Obviously, this is quite a big performance hit.
With this PR, `fork` is no longer set by stryker4s which provides a performance improvement.
Based on if the user has set `fork` (if they have, we should be able to handle it properly) the active mutation is now set in either a Setup testOption (non-forked), or `javaOptions` (forked, same as before).
It also means some java properties passing code can be removed. When fork is enabled it is now always done by the user, so any setup should already be done by them.
> perf(sbt): don't fork every test-run

- core/src/main/scala/stryker4s/config/Config.scala
- core/src/main/scala/stryker4s/config/DashboardOptions.scala
- core/src/main/scala/stryker4s/config/ExcludedMutations.scala
- core/src/main/scala/stryker4s/config/TestRunner.scala
- core/src/main/scala/stryker4s/config/Thresholds.scala
- core/src/main/scala/stryker4s/extension/mutationtype/ArgMethodExpression.scala
- core/src/main/scala/stryker4s/extension/mutationtype/MutationTypes.scala
- core/src/main/scala/stryker4s/extension/mutationtype/NoArgMethodExpression.scala
- core/src/main/scala/stryker4s/files/fileIO.scala
- core/src/main/scala/stryker4s/model/Mutant.scala
- core/src/main/scala/stryker4s/model/MutantRunResult.scala
- core/src/main/scala/stryker4s/model/MutatedFile.scala
- core/src/main/scala/stryker4s/model/MutationsInSource.scala
- core/src/main/scala/stryker4s/model/TransformedMutants.scala
- core/src/main/scala/stryker4s/report/MutationRunReporter.scala
- core/src/main/scala/stryker4s/report/dashboard/Providers.scala
- core/src/main/scala/stryker4s/report/model/DashboardConfig.scala
- core/src/main/scala/stryker4s/report/model/Href.scala
- core/src/main/scala/stryker4s/report/model/ScoreOnlyReport.scala
- core/src/main/scala/stryker4s/run/process/Command.scala
- core/src/test/resources/fileTests/filledDir/src/main/scala/package/target.scala
- core/src/test/resources/scalaFiles/ExampleClass.scala
- core/src/test/scala/stryker4s/extension/mutationtype/MutationTypesTest.scala
- core/src/test/scala/stryker4s/mutants/findmutants/MutantFinderTest.scala
- core/src/test/scala/stryker4s/report/ReporterTest.scala
- runners/command-runner/src/main/scala/stryker4s/command/config/ProcessRunnerConfig.scala
> Change most case classes/traits to be final/sealed

- docs/CONFIGURATION.md
> (docs) log-level can't be set in stryker4s.conf

- docs/CONFIGURATION.md
- maven/src/main/scala/stryker4s/maven/runner/MavenMutantRunner.scala
- maven/src/test/scala/stryker4s/maven/runner/MavenMutantRunnerTest.scala
> Add test-filter to maven plugin

- sbt/src/main/scala/stryker4s/sbt/runner/SbtMutantRunner.scala
> Add unused:locals to scalacOptions blacklist

- command-runner/src/main/scala/stryker4s/command/Stryker4sArgumentHandler.scala
- command-runner/src/main/scala/stryker4s/command/Stryker4sMain.scala
- command-runner/src/test/scala/stryker4s/run/ProcessMutantRunnerTest.scala
- command-runner/src/test/scala/stryker4s/run/Stryker4sArgumentHandlerTest.scala
- core/src/main/scala/stryker4s/files/fileIO.scala
- core/src/main/scala/stryker4s/report/ConsoleReporter.scala
- core/src/main/scala/stryker4s/report/DashboardReporter.scala
- core/src/main/scala/stryker4s/report/HtmlReporter.scala
- core/src/main/scala/stryker4s/report/JsonReporter.scala
- core/src/main/scala/stryker4s/report/MutationRunReporter.scala
- core/src/main/scala/stryker4s/report/Reporter.scala
- core/src/main/scala/stryker4s/run/MutantRunner.scala
- core/src/main/scala/stryker4s/run/Stryker4sRunner.scala
- core/src/main/scala/stryker4s/run/process/ProcessRunner.scala
- core/src/test/scala/stryker4s/Stryker4sTest.scala
- core/src/test/scala/stryker4s/report/ConsoleReporterTest.scala
- core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
- core/src/test/scala/stryker4s/report/HtmlReporterTest.scala
- core/src/test/scala/stryker4s/report/JsonReporterTest.scala
- core/src/test/scala/stryker4s/report/ReporterTest.scala
- core/src/test/scala/stryker4s/testutil/Stryker4sSuite.scala
- maven/src/main/scala/stryker4s/maven/Stryker4sMain.scala
- project/Dependencies.scala
- project/Settings.scala
- sbt/src/main/scala/stryker4s/sbt/Stryker4sMain.scala
Introduces cats-effect and fs2 instead of a `Future` based system for reporters. Plan is to expand the usage later on, but for now this is a good starting point
> Introduce cats-effect, fs2 for reporters

- core/src/main/scala/stryker4s/files/fileIO.scala
- core/src/main/scala/stryker4s/report/HtmlReporter.scala
- core/src/main/scala/stryker4s/report/Reporter.scala
- core/src/test/scala/stryker4s/report/ConsoleReporterTest.scala
- core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
- core/src/test/scala/stryker4s/report/HtmlReporterTest.scala
- core/src/test/scala/stryker4s/report/JsonReporterTest.scala
- core/src/test/scala/stryker4s/report/ReporterTest.scala
- core/src/test/scala/stryker4s/testutil/Stryker4sSuite.scala
File writing and tests were broken since move to fs2. Now uses unsafeRunSync instead of unsafeToFuture
> Fix file reporters not writing to file

- command-runner/src/main/scala/stryker4s/command/Stryker4sMain.scala
- core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
- core/src/main/scala/stryker4s/report/dashboard/DashboardConfigProvider.scala
- core/src/test/scala/stryker4s/Stryker4sTest.scala
- core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
- core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
- core/src/test/scala/stryker4s/mutants/applymutants/StatementTransformerTest.scala
- core/src/test/scala/stryker4s/mutants/findmutants/FileCollectorTest.scala
- core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
- core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
- core/src/test/scala/stryker4s/report/HtmlReporterTest.scala
- core/src/test/scala/stryker4s/report/mapper/MutantRunResultMapperTest.scala
- project/Dependencies.scala
Tests are failing due to a new pureconfig release that is needed
> Update Scala 2.13 to 2.13.3

- .github/workflows/ci.yml
Looking carefully at the logging the sbt scripted tests are not running 😐
> Fix sbt scripted tests not running

- core/src/main/scala/stryker4s/extension/TreeExtensions.scala
- core/src/test/scala/stryker4s/extension/TreeExtensionsTest.scala
- core/src/test/scala/stryker4s/mutants/AddAllMutationsTest.scala
> Fix some mutations in if-statements not being applied

- .github/workflows/ci.yml
- .github/workflows/mutation-testing.yml
- .github/workflows/release.yml
Setup-java has a bigger user-base and provides the same features for us
> Use setup-java instead of setup-scala

- .github/workflows/ci.yml
- .github/workflows/mutation-testing.yml
- .github/workflows/release.yml
- project/build.properties
Seems like setup-java has some more issues than expected. Could be related to sbt or java distros? I am not sure
> Go back to setup-scala

- .github/workflows/ci.yml
- project/Dependencies.scala
- project/Settings.scala
Update dotty 0.27.0-RC1 to Scala 3.0.0-M1. This should also fix the failing release pipeline in the master branch
> Update dotty to Scala 3.0.0-M1

- docs/configuration.md
Small changes that improve the configuration docs.
> docs(configuration): fancify the configuration docs

- .github/workflows/release.yml
- maven/pom.xml
sbt-ci-release now works with gpg 2 which is already installed on gh actions 🎉
> Use gpg2 to sign releases

- command-runner/src/main/scala/stryker4s/command/Stryker4sCommandRunner.scala
- command-runner/src/main/scala/stryker4s/command/runner/ProcessTestRunner.scala
- command-runner/src/test/scala/stryker4s/run/ProcessTestRunnerTest.scala
- core/src/main/scala/stryker4s/run/process/ProcessResource.scala
- core/src/main/scala/stryker4s/run/process/ProcessRunner.scala
- core/src/main/scala/stryker4s/run/process/UnixProcessRunner.scala
- core/src/main/scala/stryker4s/run/process/WindowsProcessRunner.scala
- core/src/test/scala/stryker4s/mutants/findmutants/FileCollectorTest.scala
- core/src/test/scala/stryker4s/run/process/ProcessRunnerTest.scala
- core/src/test/scala/stryker4s/testutil/stubs/TestProcessRunner.scala
- core/src/test/scala/stryker4s/testutil/stubs/TestRunnerStub.scala
- sbt/src/main/scala/stryker4s/sbt/runner/ProcessTestRunner.scala
Adds support for timeout test-runner based on the initial test-run duration for the command-runner
> Add support for timeout based on initial test in command-runner

- project/Dependencies.scala
- project/Settings.scala
This gave more problems than it's worth 😢
> Remove direct dependency on sttp-model

- project/Dependencies.scala
> Update Scala 3 RC-3 to 3.0.0

- core/src/main/scala/stryker4s/extension/TreeExtensions.scala
- core/src/main/scala/stryker4s/extension/mutationtype/MutationTypes.scala
- core/src/main/scala/stryker4s/extension/mutationtype/StringLiteral.scala
- core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
- core/src/test/scala/stryker4s/mutants/findmutants/MutantMatcherTest.scala
> Fix type literals being mutated when they shouldn't be

- core/src/main/scala/stryker4s/extension/TreeExtensions.scala
- core/src/test/scala/stryker4s/extension/TreeExtensionsTest.scala
- core/src/test/scala/stryker4s/mutants/AddAllMutationsTest.scala
- core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
- project/plugins.sbt
> Fix some if-statements with blocks not mutating

- sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala
- sbt/src/sbt-test/sbt-stryker4s/test-1/src/test/scala/example/IgnoreMeTest.scala
> Fix test-filter on new sbt testrunner

- command-runner/src/main/scala/stryker4s/command/runner/ProcessTestRunner.scala
- command-runner/src/test/scala/stryker4s/run/ProcessTestRunnerTest.scala
- core/src/main/scala/stryker4s/model/InitialTestRunCoverageReport.scala
- core/src/main/scala/stryker4s/run/MutantRunner.scala
- core/src/main/scala/stryker4s/run/TestRunner.scala
- core/src/main/scala/stryker4s/run/package.scala
- core/src/test/scala/stryker4s/run/TestRunnerTest.scala
- core/src/test/scala/stryker4s/testutil/stubs/TestRunnerStub.scala
- maven/src/main/scala/stryker4s/maven/runner/MavenTestRunner.scala
- maven/src/test/scala/stryker4s/maven/runner/MavenTestRunnerTest.scala
- sbt/src/main/scala/stryker4s/sbt/runner/LegacySbtTestRunner.scala
- sbt/src/main/scala/stryker4s/sbt/runner/ProcessTestRunner.scala
Now uses the average of the two runs.
Also adds some tests for the TestRunner wrappers ✌
> Fix timeout using both initial test run times together

- core/src/test/scala/stryker4s/run/TestRunnerTest.scala
- sbt/src/main/scala/stryker4s/sbt/runner/TestRunnerConnection.scala
> Fix Timeout not working on new sbt testrunner

- core/src/main/scala/stryker4s/extension/TreeExtensions.scala
- core/src/test/scala/stryker4s/extension/TreeExtensionsTest.scala
- core/src/test/scala/stryker4s/mutants/AddAllMutationsTest.scala
- core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
Slightly edits mutant placing logic so pattern match mutations are placed higher
> Fix some case statements not mutating

- core/src/test/scala/stryker4s/mutants/applymutants/MatchBuilderTest.scala
> Add test for mutations inside wildcard anonymous functions

- sbt-testrunner/src/main/scala/stryker4s/sbt/testrunner/SbtTestRunnerMain.scala
- sbt/src/main/scala/stryker4s/sbt/runner/ProcessTestRunner.scala
> Use loopback address for testrunner comms.

- core/src/main/scala/stryker4s/report/mapper/MutantRunResultMapper.scala
- core/src/test/scala/stryker4s/report/mapper/MutantRunResultMapperTest.scala
> Fix crash on Java <11 at end of mutation run

- docs/configuration.md
- docs/contributing.md
Just a few typo fixes in the documentation. Looking forward to trying this out! Thank you 🙏
> Documentation fixes

- command-runner/src/main/scala/stryker4s/command/Stryker4sMain.scala
- command-runner/src/main/scala/stryker4s/log/Slf4jLogger.scala
- core/src/main/scala/stryker4s/config/ConfigReader.scala
- core/src/main/scala/stryker4s/extension/exception/stryker4sException.scala
- core/src/main/scala/stryker4s/log/Logger.scala
- core/src/main/scala/stryker4s/mutants/Mutator.scala
- core/src/main/scala/stryker4s/mutants/findmutants/MutantMatcher.scala
- core/src/main/scala/stryker4s/report/ConsoleReporter.scala
- core/src/main/scala/stryker4s/report/DashboardReporter.scala
- core/src/main/scala/stryker4s/run/MutantRunner.scala
- core/src/main/scala/stryker4s/run/TestRunner.scala
- core/src/test/scala/stryker4s/config/ConfigReaderTest.scala
- core/src/test/scala/stryker4s/extension/exception/Stryker4sExceptionTest.scala
- core/src/test/scala/stryker4s/mutants/MutatorTest.scala
- core/src/test/scala/stryker4s/report/ConsoleReporterTest.scala
- core/src/test/scala/stryker4s/report/DashboardReporterTest.scala
- core/src/test/scala/stryker4s/run/TestRunnerTest.scala
- core/src/test/scala/stryker4s/run/threshold/ThresholdCheckerTest.scala
- core/src/test/scala/stryker4s/scalatest/LogMatchers.scala
- core/src/test/scala/stryker4s/testutil/TestLogger.scala
- maven/src/main/scala/stryker4s/log/MavenMojoLogger.scala
- project/Dependencies.scala
- project/Settings.scala
- sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala
- sbt/src/main/scala/stryker4s/sbt/runner/TestRunnerConnection.scala
Try to 'guess' via environment variables if ansi output is supported. Setting `NO_COLOR` env variable will always disable color.
> Add colors to console output

- docs/configuration.md
It's not CamelCase that is used, but rather kebab-case.
> minor typo in docs

- README.md
- sbt/src/sbt-test/sbt-stryker4s/test-1/README.md
> Two small documentation fixes

- core/src/main/scala/stryker4s/run/MutantRunner.scala
Fixes https://github.com/stryker-mutator/stryker4s/issues/1219,
Fixes https://github.com/stryker-mutator/stryker4s/issues/1415
> [core] Use config Dialect to write Scala3 mutations

- project/Settings.scala
> Fix releases by disabling sbt-tpolecat release mode

- .github/dependabot.yml
- maven/pom.xml
Reverts stryker-mutator/stryker4s#1546
> Revert "build(deps): bump project.version from SET-BY-SBT-SNAPSHOT to 0.16.1 in /maven"

- docs/configuration.md
Fix one broke link in the documentation
> docs: update github link for full list of scala dialect

- modules/core/src/main/scala/stryker4s/extension/FileExtensions.scala
- modules/core/src/test/scala/stryker4s/extension/FileExtensionsTest.scala
- modules/sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala
- **chore: update stryker4s to 0.17.0**
- **Remove stryker4s config files**
- **fix: handle relative paths correctly when fixing compile errors**
> fix comp error path handling

- modules/core/src/main/scala/stryker4s/report/ConsoleReporter.scala
- modules/core/src/test/scala/stryker4s/report/ConsoleReporterTest.scala
If it is different to the total score
Related to #1755
> feat(console-reporter): report score based on covered code

- .github/workflows/ci.yml
- modules/core/src/main/scala/stryker4s/extension/ResourceExtensions.scala
- modules/core/src/main/scala/stryker4s/files/desktopIO.scala
- modules/core/src/main/scala/stryker4s/report/HtmlReporter.scala
- modules/core/src/main/scala/stryker4s/run/process/ProcessResource.scala
- modules/core/src/main/scala/stryker4s/run/process/ProcessRunner.scala
- modules/core/src/test/scala/stryker4s/run/MutantRunnerTest.scala
- modules/sbt/src/main/scala/stryker4s/model/TestRunnerId.scala
- modules/sbt/src/main/scala/stryker4s/sbt/Stryker4sSbtRunner.scala
- modules/sbt/src/main/scala/stryker4s/sbt/runner/ProcessTestRunner.scala
- modules/sbt/src/main/scala/stryker4s/sbt/runner/SbtTestRunner.scala
- modules/sbt/src/main/scala/stryker4s/sbt/runner/TestRunnerConnection.scala
- modules/sbt/src/sbt-test/sbt-stryker4s/test-1/build.sbt
- modules/sbtTestRunner/src/main/scala/stryker4s/sbt/testrunner/Context.scala
- modules/sbtTestRunner/src/main/scala/stryker4s/sbt/testrunner/SbtTestRunnerMain.scala
- modules/sbtTestRunner/src/main/scala/stryker4s/sbt/testrunner/server/TcpSocketServer.scala
- modules/sbtTestRunner/src/main/scala/stryker4s/sbt/testrunner/server/UnixSocketServer.scala
- modules/testRunnerApi/src/main/scala/stryker4s/testrunner/api/TestProcessProperties.scala
- project/Dependencies.scala
- project/Settings.scala
And fallback to TCP if not
Using new FS2 and Cats unix sockets
> feat: connect to testrunner over unix sockets, if available
